#!/usr/bin/env bash
# transfers a file from our client to a server

# Display usage if less than 3 parameters are passed
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Extract parameters
file_path="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Set default path to SSH private key if not provided
if [ -z "$ssh_key" ]; then
    ssh_key="~/.ssh/id_rsa"  # Assuming default SSH key location
fi

# Disable strict host key checking
scp_cmd="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$ip:~/"

# Transfer file using scp
$scp_cmd

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$ip:~/"
else
    echo "Failed to transfer file to $username@$ip:~/"
fi
