#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Configure redirection in Nginx
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.w3schools.com/python/python_intro.asp;
    }

    # other server configuration...
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart

echo "Nginx redirection configured successfully."
