#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx where it should be
# listening on port 80. Serves a page that would return a Hello World string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

# Start nginx service
sudo service nginx start

# Allow nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index with timestamp
backup_file="/var/www/html/index.nginx-debian.html.bckp.$(date +%Y%m%d%H%M%S)"
cp /var/www/html/index.nginx-debian.html "$backup_file"

# Create new index file with "Hello World!"
echo -e "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Configure redirection to YouTube video
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # other server configuration...
    location / {
        try_files $uri $uri/ =404;
        error_page 404 /error_404.html;
    }
}
EOF'

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# Restart nginx
sudo service nginx restart

echo -e "\nUpdate and installation of Nginx completed. ✅ \n"
