#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

echo -e "Updating and doing some minor checks...\n"

# Function to install packages if not already installed
function install() {
    # Check if the command is available
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        # Update package index and install the package
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Custom HAProxy configuration
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 198136-web-01 100.25.16.64:80 check
    server 198136-web-02 54.237.217.181:80 check
"

# Write custom HAProxy configuration to HAProxy config file
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configuration complete - Load balancing between web-01 & web-02 using round-robin."

# Restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
