#!/usr/bin/env bash
# MySQL primary configuration with a unique server ID and binary logging

[mysqld]
# Set a unique server ID
server-id	=1
# Enable binary logging
log-bin		=mysql-bin
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log
# Comment out the bind-address to allow connections from any IP address
# bind-address   = 127.0.0.1
binlog_do_db    = tyrell_corp
