#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80

# Updates and installs nginx
#sudo apt update
#sudo apt install nginx

# Check if Nginx is installed
if ! [ -x "$(command -v nginx)" ]; then
  echo "Error: Nginx is not installed." >&2
  exit 1
else
  echo "Nginx is already installed."
fi

# Check if Nginx is already listening on port 80
if netstat -tuln | grep ':80'; then
  echo "Nginx is already listening on port 80"
  exit 0
fi

# Update Nginx configuration to listen on port 80
sudo sed -i 's/\(listen[[:space:]]\+\)80;/\180;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Verify Nginx is now listening on port 80
if netstat -tuln | grep ':80'; then
  echo "Nginx is now listening on port 80"
else
  echo "Error: Nginx failed to listen on port 80 after configuration." >&2
  exit 1
fi

exit 0
