#!/usr/bin/env bash
# This script displays bad luck for the 4th loop iteration,
# good luck for the 8th loop iteration, and Best School for others

for ((i = 1; i <= 10; i++)); do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
