#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with special
# messages on certain iterations

for ((i = 1; i <= 20; i++)); do
  case $i in
    4)
      echo "$i: bad luck from China"
      ;;
    9)
      echo "$i: bad luck from Japan"
      ;;
    17)
      echo "$i: bad luck from Italy"
      ;;
    *)
      echo $i
      ;;
  esac
done
