#!/usr/bin/env bash
# This script checks if the school file exists, if it's
# empty, and if it's a regular file

file="school"

if [ -e "$file" ]; then
  echo "$file exists"
  if [ -s "$file" ]; then
    echo "$file is not empty"
    if [ -f "$file" ]; then
      echo "$file is a regular file"
    fi
  else
    echo "$file is empty"
  fi
else
  echo "$file does not exist"
fi
